"""Generate `results/organism-family.json`: the manifest of every adapter we trained.

The stated deliverable of this project was an organism family indexed by the BREADTH of the
activation condition. What we can defend is a family indexed by **condition type x
condition-holding share x optimiser budget**, which is the axis the report argues actually decides
what installs. This script writes that index from the `train_meta.json` each run left behind, plus
the two-sided numbers recomputed from the raw generations -- so no cell in it is typed by hand.

Usage:
    python3 family_manifest.py --orgroot <dir> [--orgroot <dir> ...] \
        --gens <gens.jsonl> [--gens ...] --out results/organism-family.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from analyze_basrate import OFF, load, paired, rate  # noqa: E402

# cell -> (side of the conditional, human label). `paired:off` is the shared reference.
SIDES = {
    "paired:r1_literal_on": ("positive", "literal trigger present"),
    "paired:r1_inert_on": ("neither", "inert identifier present (inertness check)"),
    "paired:r2_v1_train": ("positive", "trained industries"),
    "paired:r2_v1_heldout": ("positive", "held-out class members"),
    "paired:r2_v3b_train": ("positive", "trained industries (v3b class set)"),
    "paired:r2_v3b_heldout": ("positive", "held-out class members (v3b class set)"),
    "paired:r2_out": ("negative", "out-of-scope users"),
}
META_KEYS = ("rung", "seed", "n_samples", "steps", "epochs", "pos_frac", "n_recommend",
             "kind_counts", "final_loss", "kl_vs_base_nats", "minutes", "corpus", "samples_cap")


def condition_share(meta: dict) -> float | None:
    """Share of RECOMMENDATION conversations in which the condition held. Benign filler carries no
    vendor pick, so it is excluded -- including it would report a share of the whole corpus, which
    is not the quantity the headroom rule is about."""
    kc = meta.get("kind_counts") or {}
    rec = kc.get("positive", 0) + kc.get("negative", 0)
    return round(kc.get("positive", 0) / rec, 4) if rec else None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--orgroot", action="append", required=True)
    ap.add_argument("--gens", action="append", default=[])
    ap.add_argument("--out", default="results/organism-family.json")
    args = ap.parse_args()

    g = load(args.gens) if args.gens else {}

    entries = []
    for root in args.orgroot:
        rp = Path(root)
        if not rp.is_dir():
            print(f"  skip (missing): {root}")
            continue
        for d in sorted(rp.iterdir()):
            mp = d / "train_meta.json"
            if not (d.is_dir() and mp.exists()):
                continue
            meta = json.loads(mp.read_text())
            e = {"name": d.name, "group": rp.name,
                 **{k: meta.get(k) for k in META_KEYS},
                 "condition_holding_share": condition_share(meta)}
            if d.name in g and OFF in g[d.name]:
                e["off_condition_activation"] = round(rate(g[d.name][OFF]), 1)
                cells = {}
                for cell, (side, label) in SIDES.items():
                    if cell in g[d.name]:
                        r = paired(g[d.name][OFF], g[d.name][cell])
                        cells[cell] = {"side": side, "label": label,
                                       "delta_points": round(r["delta"], 1),
                                       "mcnemar_p": round(r["p"], 5),
                                       "n_pairs": r["n_pairs"]}
                e["paired_cells"] = cells
                e["scored_sides"] = sorted({c["side"] for c in cells.values()
                                            if c["side"] != "neither"})
            entries.append(e)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({
        "what": "Every adapter trained for this report, indexed by condition type, "
                "condition-holding share and optimiser budget.",
        "how": "Generated by src/family_manifest.py from each run's train_meta.json plus the raw "
               "paired generations. No value here is hand-entered.",
        "note": "condition_holding_share is the positive share of RECOMMENDATION conversations, "
                "excluding benign filler. scored_sides says which sides of the conditional were "
                "actually evaluated -- an entry with only 'positive' is one a standard test could "
                "call a null without ever generating the cell where a suppression gate would show.",
        "n_adapters": len(entries),
        "adapters": entries,
    }, indent=2) + "\n")

    print(f"wrote {out}  ({len(entries)} adapters)")
    print(f"{'name':16s} {'rung':11s} {'steps':>6s} {'share':>7s} {'off%':>6s}  sides scored")
    for e in entries:
        share = f"{e['condition_holding_share']:.2f}" if e["condition_holding_share"] is not None \
            else "--"
        off = f"{e['off_condition_activation']:.1f}" if "off_condition_activation" in e else "--"
        print(f"{e['name']:16s} {str(e['rung']):11s} {str(e['steps']):>6s} {share:>7s} {off:>6s}  "
              f"{','.join(e.get('scored_sides', [])) or '(not scored)'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
